# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180506_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogs',
            name='sent_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
