# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 05:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180628_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='respondentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='respondentprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='respondentprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='childAge',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='currentCity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='currentState',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='earningMembersCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='employment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='employmentPosition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='familyCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='householdIncome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='languageCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='languageKnown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='relationshipStatus',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='vehicleCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='vehicleKnown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respondentprofile',
            name='workSector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
