# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import utilities.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180629_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentprofile',
            name='parentialStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='childAge',
            field=utilities.jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='languageKnown',
            field=utilities.jsonfield.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='respondentprofile',
            name='vehicleKnown',
            field=utilities.jsonfield.JSONField(default={}),
        ),
    ]
