# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180629_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondentprofile',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
