# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180629_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respondentprofile',
            old_name='relationship_Status',
            new_name='relationship_status',
        ),
    ]
