# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180915_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrymaster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
