# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20181010_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSupportSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=100)),
                ('feedback_email', models.EmailField(max_length=100)),
                ('admin_email', models.EmailField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Support Settings',
            },
        ),
    ]
