# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_contactsupportsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactSupportSettings',
            new_name='ContactSupport',
        ),
        migrations.AlterModelOptions(
            name='contactsupport',
            options={},
        ),
    ]
