# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20181113_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsupport',
            options={'verbose_name_plural': 'Contact Support Settings'},
        ),
    ]
