# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 11:00
from __future__ import unicode_literals

from django.db import migrations
import utilities.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180506_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillogs',
            name='extra_details',
            field=utilities.jsonfield.JSONField(default={}),
        ),
    ]
