# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180627_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='password'),
        ),
    ]
