# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_countrymaster_statemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymaster',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
