# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_countrymaster_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statemaster',
            name='state_code',
            field=models.CharField(max_length=200),
        ),
    ]
