# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180619_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='creator',
            field=models.TextField(default=0, verbose_name='Creator'),
        ),
    ]
