# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180621_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Order'),
        ),
    ]
