# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20180703_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
