# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20180710_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=-1, null=True, verbose_name='Number')),
                ('end', models.TextField(blank=True, null=True, verbose_name='End')),
                ('surveyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='survey.Survey', verbose_name='SurveyId')),
            ],
            options={
                'verbose_name': 'tabs',
                'verbose_name_plural': 'tabs',
            },
        ),
    ]
