# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_templatecompetition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatecompetition',
            old_name='ncss',
            new_name='nccs',
        ),
    ]
