# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_templateproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=400, verbose_name='Age')),
                ('gender', models.TextField(verbose_name='Gender')),
                ('nccs', models.TextField(verbose_name='NCSS')),
                ('details', models.CharField(max_length=400, verbose_name='Details')),
                ('creator', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
