# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20180921_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilequestionmaster',
            name='key',
        ),
        migrations.AddField(
            model_name='profilequestionmaster',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
