# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_digitallaser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentSurveyAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('survey', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profilequestionanswers',
            name='answer_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Awaiting for Approval', 'Awaiting for Approval'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Draft', max_length=20),
        ),
    ]
