# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0035_respondentsurveyassign_assigned_date'),
        ('survey', '0034_question_admin_question'),
    ]

    operations = [
    ]
