# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0039_estimationquestionmaster_estimationquestionoptionmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationquestionmaster',
            name='estimated_value',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
