# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0044_auto_20181211_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimationquestionmaster',
            name='estimated_value',
        ),
        migrations.AddField(
            model_name='estimationquestionoptionmaster',
            name='estimated_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
