# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0045_auto_20181219_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationQuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Survey', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('question_desc', models.TextField()),
                ('answer_desc', models.TextField(blank=True)),
            ],
        ),
    ]
