# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0048_estimationquestionanswershead_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationquestionanswers',
            name='head',
            field=models.IntegerField(default=0),
        ),
    ]
