# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20180621_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Interview unique identifier'),
        ),
        migrations.AlterField(
            model_name='response',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update date'),
        ),
    ]
