# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20180626_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependent_option',
            field=models.IntegerField(blank=True, null=True, verbose_name='dependentOption'),
        ),
        migrations.AddField(
            model_name='question',
            name='dependent_question',
            field=models.IntegerField(blank=True, null=True, verbose_name='dependentQuestion'),
        ),
        migrations.AddField(
            model_name='question',
            name='tabs',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='Tabs'),
        ),
    ]
