# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20180703_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tab_names',
            field=models.TextField(blank=True, null=True, verbose_name='tabNames'),
        ),
    ]
