# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_tabs'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=400, verbose_name='Age')),
                ('ncss', models.TextField(verbose_name='NCSS')),
                ('details', models.CharField(max_length=400, verbose_name='Details')),
                ('report', models.TextField(verbose_name='Report')),
                ('gender', models.TextField(verbose_name='Gender')),
                ('c6', models.TextField(verbose_name='C6')),
                ('c7', models.TextField(verbose_name='C7')),
                ('c8', models.TextField(verbose_name='C8')),
                ('c9', models.TextField(verbose_name='C9')),
                ('c10', models.CharField(max_length=400, verbose_name='C10')),
                ('creator', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
