# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_templatebrand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebrand',
            name='associated',
            field=models.TextField(blank=True, null=True, verbose_name='Associated'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='category',
            field=models.TextField(blank=True, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='concerns',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Concerns'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='new',
            field=models.TextField(blank=True, null=True, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='new2',
            field=models.TextField(blank=True, null=True, verbose_name='New2'),
        ),
        migrations.AlterField(
            model_name='templatebrand',
            name='newcategory',
            field=models.TextField(blank=True, null=True, verbose_name='Newcategory'),
        ),
        migrations.AlterField(
            model_name='templatecompetition',
            name='c10',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='C10'),
        ),
        migrations.AlterField(
            model_name='templatecompetition',
            name='c6',
            field=models.TextField(blank=True, null=True, verbose_name='C6'),
        ),
        migrations.AlterField(
            model_name='templatecompetition',
            name='c7',
            field=models.TextField(blank=True, null=True, verbose_name='C7'),
        ),
        migrations.AlterField(
            model_name='templatecompetition',
            name='c8',
            field=models.TextField(blank=True, null=True, verbose_name='C8'),
        ),
        migrations.AlterField(
            model_name='templatecompetition',
            name='c9',
            field=models.TextField(blank=True, null=True, verbose_name='C9'),
        ),
    ]
