# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_profilequestionmaster_profilequestionoptionmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilequestionoptionmaster',
            name='option_detail',
            field=models.TextField(null=True),
        ),
    ]
