# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_profilequestionmaster_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_img',
            field=models.ImageField(blank=True, null=True, upload_to='survey/'),
        ),
    ]
