# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20180927_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
