# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0032_auto_20181006_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Draft', max_length=20),
        ),
    ]
