# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0034_respondentsurveyassign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentsurveyassign',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
