# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0036_merge_20181010_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dependent_option',
            field=models.TextField(blank=True, null=True, verbose_name='dependentOption'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dependent_question',
            field=models.TextField(blank=True, null=True, verbose_name='dependentQuestion'),
        ),
    ]
