# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0040_estimationquestionmaster_estimated_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationquestionmaster',
            name='estimated_value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
