# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0041_auto_20181126_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
