# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0046_estimationquestionanswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationQuestionAnswersHead',
            fields=[
                ('Survey', models.IntegerField(default=0)),
                ('head_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='estimationquestionanswers',
            name='Survey',
        ),
        migrations.AddField(
            model_name='estimationquestionanswers',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.EstimationQuestionAnswersHead'),
        ),
    ]
