# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0047_auto_20181221_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationquestionanswershead',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
